### ISSUE TITLE
Fetching from npm failed: certificate not trusted

### ISSUE THREAD

**Issue by niuba** [BenBBear/cordova-plugin-leanpush#1]
Fetching plugin "cordova-plugin-leanpush" via npm
npm http GET https://registry.npm.taobao.org/cordova-plugin-leanpush
npm http GET https://registry.npm.taobao.org/cordova-plugin-leanpush
npm http GET https://registry.npm.taobao.org/cordova-plugin-leanpush
Fetching from npm failed: certificate not trusted
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

**Comment by mlzxy** [comment]
> npm http GET https://registry.npm.taobao.org/cordova-plugin-leanpush

你的npm源是淘宝的， 下载cordova插件可能必须使用npm官方源（cordova最近才迁移到npm， 可能还不支持cnpm的同步）

<img width="647" alt="2015-07-16 12 23 20" src="https://cloud.githubusercontent.com/assets/7659710/8715488/590f69ca-2bb5-11e5-9c94-3cde3fb13ae6.png">

这个是我运行的结果

**Comment by mlzxy** [comment]
cordova内部调用的应该是npm， 估计你改了npm的全局registry设置了， 改过来试一下 :)

**Comment by niuba** [comment]
soga thanks
