### ISSUE TITLE
是否支持声音播放

### ISSUE THREAD

**Issue by kongkang** [BenBBear/cordova-plugin-leanpush#14]
首先感恩这么好的插件（发自肺腑的感觉方便了很多工作！！！

想问下插件中是否支持声音？
简单搜索了一下sound，貌似并没有。

如果支持，求作者简单提示，剩下我自己查资料或补代码。
（已经用了插件，已经没脸做伸手坐等党了……但确实不会任何原生代码，项目时间也不允许现学

**Comment by kongkang** [comment]
额，好像是我傻逼了，自己回答吧，方便以后的人：

推送的时候，可以加声音参数：

```
        "data": {
          "alert": "本周五下午三点组织大家看电影《大圣归来》。",
          "badge": "Increment",
          "sound": "cheering.caf",
          "title": "员工福利"
        }
```

参考文档：[定制消息属性](https://leancloud.cn/docs/push_guide.html#定制消息属性_)

**Comment by kongkang** [comment]
再加一个可能是的坑，方便后人。

声音文件必须是用xcode导入的，光在ionic里面加，不行。
推荐目录resource里面

**Comment by diegozhu** [comment]
冒似只有iOS支持sound参数吧？
