### ISSUE TITLE
Xcode真机运行报错

### ISSUE THREAD

**Issue by puny-d** [BenBBear/cordova-plugin-leanpush#3]
你好，我在使用这个插件的时候，发现Xcode编译总是会报错：
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AVInstallation", referenced from:
      objc-class-ref in CDVLeanPush.o
      objc-class-ref in AppDelegate+LeanPush.o
  "_OBJC_CLASS_$_AVOSCloud", referenced from:
      objc-class-ref in AppDelegate+LeanPush.o
  "_OBJC_CLASS_$_AVAnalytics", referenced from:
      objc-class-ref in CDVLeanAnalytics.o
      objc-class-ref in AppDelegate+LeanPush.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mlzxy** [comment]
猫似找不到很多symbol

`AVInstallation`和 `AVAnalytics` 都应该出自 AVOSCloud.framework （leancloud的ios sdk）， 这个库文件应该在：
`/yourAppRoot/platforms/ios/yourAppName/Plugins/cordova-plugin-leanpush/` 这个目录里面， 你可以看看有没有（应该是有的）

把这个库加入project的声明语句在 `/yourAppRoot/plugins/cordova-plugin-leanpush/plugin.xml` 

``` xml
  <framework src="src/ios/Frameworks/AVOSCloud.framework" custom="true"/>
```

如果这两个地方都没问题， 你可以尝试把插件重装， 之后`ionic platform rm ios && ionic platform add ios` 重置一下

**Comment by mlzxy** [comment]
有可能是你下载插件或者初始化项目的时候， 网络出了些小问题

**Comment by puny-d** [comment]
真是非常感谢！我重新add platform后，这个问题解决了，但是我在订阅频道的时候，始终无法成功，我在leancloud后台看到的永远是空数组，下面是我的Xcode的报错。
[7351:1852571] CDVLeanPush subscribe (
    ABC
)
[7351:1852571] -[__NSArrayM length]: unrecognized selector sent to instance 0x17024a110
[7351:1852571] **\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSArrayM length]: unrecognized selector sent to instance 0x17024a110

**Comment by mlzxy** [comment]
能否给出一些出错的js代码示例？ 这样我可以尝试重现这种错误

**Comment by puny-d** [comment]
好的，这是我的JS代码，leancloud后台显示了这个install，说明插件应该是运行正确的，就是不知道为啥订阅一直不行。

```
window.LeanPush.init();
window.LeanPush.clearSubscription(function () {
        window.LeanPush.subscribe(['ABC'], function () {

            console.log('订阅成功');

        }, function (err) {
            console.log(err);
        });
    }, function (err) {
        console.log(err);
 });

    window.LeanPush.getInstallation(function (data) {
        console.log(data);
    }, function (err) {
        console.log(err);
    });
```

**Comment by mlzxy** [comment]
subscribe部分js代码是：

``` js
 subscribe =  function(channel, success, error) {
        console.log('subscribe', channel);
        exec(success, error, "LeanPush", "subscribe", [channel]);
    }
```

所以你试着把channel换成一个string试一下吧 😶

**Comment by puny-d** [comment]
非常感谢，还真是这样，我是按照官方的js sdk作为参考，还以为要传入数组。建议你可以这里更新一下文档，防止给后来者造成误导。

**Comment by mlzxy** [comment]
好的
