### ISSUE TITLE
leancloud管理台没有installation数据

### ISSUE THREAD

**Issue by ramsaylee** [BenBBear/cordova-plugin-leanpush#6]
你好，
非常感谢分享这个插件，我
1. 按照文档介绍安装好了这个插件
2. 在$ionicPlatform.ready中加入了window.LeanPush.init();
3. 在XCode里打包出IPA
4. 在分发平台（蒲公英）分发并安装
5. 启动App
但是并没有在leancloud管理台中看到installation数据，请问一下我哪里做的有问题呢？我对这块也不太熟。

感谢！

**Comment by ramsaylee** [comment]
还有就是在打包的时候，报了两个警告
/.../app/platforms/ios/app/Plugins/cordova-plugin-leanpush/AppDelegate+LeanPush.m:117:13: Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'
/.../app/platforms/ios/app/Plugins/cordova-plugin-leanpush/AppDelegate+LeanPush.m:172:15: Implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'

不知道有没有什么影响？

**Comment by ramsaylee** [comment]
再补充点信息，在simulator控制台看到的log
0     849336   log
1     849339   log
2     849586   log      ready
3     849588   log      LeanPush Initialization
4     849589   log      clearSubscription
5     849590   log      getInstallation
6     849609   log      subscribe, test
7     849610   log      Fail to get Installation.
8     849611   log      订阅成功

对应的代码
            console.log('ready');
            window.LeanPush.init();
            window.LeanPush.clearSubscription(function() {
                window.LeanPush.subscribe('test', function() {
                    console.log('订阅成功');
                }, function(err) {
                    console.log(err);
                });
            }, function(err) {
                console.log(err);
            });

```
        window.LeanPush.getInstallation(function(data) {
            console.log(data);
        }, function(err) {
            console.log(err);
        });
```

**Comment by ramsaylee** [comment]
这个问题解决了，还是证书的问题。不过现在又有新问题了：
在leancloud那边installation里面有了记录，在线发送也成功了，在notification表里也有了记录，但是机器上并没有收到推送，请问一下这是什么问题？谢谢！

**Comment by mlzxy** [comment]
有几种可能性， 
1. 证书dev/prod问题， 如果测试时，xcode安装在device上的app是dev profile， 所以接受不到prod推送（且prod为默认选项，见 https://leancloud.cn/docs/js_guide.html#Push_通知）
2. 看一下 web界面里面notification表中，subscribers属性和invalidTokens属性，可能由于各种原因失败，变成 invalidTokens

最近自己有点忙， 可能回复不会很及时哈，sorry

**Comment by ramsaylee** [comment]
@BenBBear 非常感谢，真的是证书prod/dev的问题，现在已经搞好了。
