### ISSUE TITLE
install脚本太难读了

### ISSUE THREAD

**Issue by xixilive** [BenBBear/cordova-plugin-leanpush#7]
建议用async之类的重构一下

**Comment by mlzxy** [comment]
其实我也早就想重写。

已经重写， 见新版：

https://github.com/BenBBear/cordova-plugin-leanpush/blob/master/lpush-installer.js

正在`npm publish`, 不过网速太慢了。。。

**Comment by mlzxy** [comment]
publish上去了 :D

**Comment by xixilive** [comment]
:+1:
