### ISSUE TITLE
我觉得应该将install script的依赖加入到package.json

### ISSUE THREAD

**Issue by xixilive** [BenBBear/cordova-plugin-leanpush#8]
such as:

```
"optionalDependencies": {
  "xml2js": "SEM_VER",
  "thunk": "SEM_VER"
}
```

**Comment by mlzxy** [comment]
自己是通过

``` shell
npm install --save-dev xml2js thunks
```

安装的依赖， 还没有试过在cordova的package.json中添加依赖， 因为也没试过， 我是试试哈

**Comment by mlzxy** [comment]
https://github.com/BenBBear/cordova-plugin-leanpush/blob/master/package.json#L30

加入了， 但是似乎

```
ionic plugin add plugin-name
```

的时候并不会自动更改项目的package.json

**Comment by xixilive** [comment]
我个人觉得对于这个plugin, 因为有安装参数依赖(AppID, AppKey...), 所以建议提供[npm executable script](https://docs.npmjs.com/files/package.json#bin)  让用户去从命令行运行, 同时, 提供gulp/grunt task module, 以便开发者在其自己的构建工具下使用.

```
# shell
lpush setup --id=XXX --key=XXX
```

```
//grunt task module
module.exports = function(grunt){
  grunt.registerTask(......)
}

//gulp task module
var gutil = require("gulp-util");
module.exports = function(options){
  ....
}
```

纠正一下, 根据场景, 可能需要必选依赖, 而不是dev或者optional.

**Comment by mlzxy** [comment]
@xixilive 

恩恩， 手动设置 package name， app id, app key也是有好处的， 自动解析相关xml文件可能会出错。

不过现在也足够简单了， 这方面应该暂时不需要更多修改了
